import styles from '../styles/module/terms.module.css'
import Header from './header'
import { motion } from 'framer-motion'

const Terms = () => {
  return (
    <>
      <Header />
      <motion.div
        className={`${styles.main_container}`}
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 1.5 }}
      >
        <div className={`${styles.wrapper} `}>
          <div className={`${styles.section_one} `}>
            <h1>TERMS & CONDITIONS</h1>
            <p>
              Crypto Alpha Skullz Club is a collection of digital artworks (NFTs) running on the Ethereum network. This website is only an interface allowing participants to exchange digital collectibles. Users are entirely responsible for the safety and management of their own private Ethereum wallets and validating all transactions and contracts generated by this website before approval. Furthermore, as the Crypto Alpha Skullz Club smart contract runs on the Ethereum network, there is no ability to undo, reverse, or restore any transactions.
            </p>
            <br />
            <p>
              This website and its connected services are provided “as is” and “as available” without warranty of any kind. By using this website you are accepting sole responsibility for any and all transactions involving Crypto Alpha Skullz Club digital collectibles.
            </p>
          </div>
          <div className={`${styles.section_two} `}>
            <h2>OWNERSHIP</h2>
            <p>
              i. You Own the NFT. Each Alpha Skullz is an NFT on the Ethereum blockchain. When you purchase an NFT, you own the underlying  Alpha Skullz, the Art, completely. Ownership of the NFT is mediated entirely by the Smart Contract and the Ethereum Network: at no point may we seize, freeze, or otherwise modify the ownership of any  Alpha Skullz.
            </p>
            <br />
            <p>
              ii. Personal Use. Subject to your continued compliance with these Terms, Yuga Labs LLC grants you a worldwide, royalty-free license to use, copy, and display the purchased Art, along with any extensions that you choose to create or use, solely forthe following purposes: (i) for your own personal, non-commercial use; (ii) as part of a marketplace that permits the purchase and sale of your Alpha Skull / NFT, provided that the marketplace cryptographically verifies each Alpha Skull owner’s rights to display the Art for their Alpha Skullz to ensure that only the actual owner can display the Art; or (iii) as part of a third party website or application that permits the inclusion, involvement, or participation of your Alpha Skullz, provided that the website/application cryptographically verifies each Alpha Skull owner’s rights to display the Art for their Alpha Skull to ensure that only the actual owner can display the Art, and provided that the Art is no longer visible once the owner ofthe Alpha Skull leaves the website/application.
            </p>
            <br />
            <p>
              iii. Commercial Use. Subject to your continued compliance with these Terms, Yuga Labs LLC grants you an unlimited, worldwide license to use, copy, and display the purchased Art for the purpose of creating derivative works based upon the Art (“Commercial Use”). Examples of such Commercial Use would e.g. be the use of the Art to produce and sell merchandise products (T-Shirts etc.) displaying copies of the Art. For the sake of clarity, nothing in this Section will be deemed to restrict you from (i) owning or operating a marketplace that permits the use and sale of Alpha Skull generally, provided that the marketplace cryptographically verifies each Alpha Skull owner’s rights to display the Art for their Alpha Skull to ensure that only the actual owner can display the Art; (ii) owning or operating a third party website or application that permits the inclusion, involvement, or participation of Alpha Skull generally, provided that the third party website or application cryptographically verifies each Alpha Skull owner’s rights to display the Art for their Alpha Skull to ensure that only the actual owner can display the Art, and provided that the Art is no longer visible once the owner of the Purchased Alpha Skull leaves the website/application; or (iii) earning revenue from any of the foregoing.
            </p>
          </div>
        </div>
        <div className={`${styles.footer_divider} `}></div>
      </motion.div>
    </>
  )
}

export default Terms